# Generated by Django 2.2.10 on 2020-06-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('main_image', models.ImageField(blank=True, upload_to='post/%Y/%m/%d')),
                ('body1', models.TextField(blank=True)),
                ('quote', models.TextField()),
                ('body2', models.TextField()),
                ('sub_title', models.CharField(max_length=250)),
                ('body3', models.TextField()),
                ('sub_image', models.ImageField(upload_to='post/%Y/%m/%d')),
                ('body4', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modifield', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='blog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
