# Generated by Django 2.2.10 on 2020-06-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='body1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(upload_to='post/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_image',
            field=models.ImageField(blank=True, upload_to='post/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
