# Generated by Django 2.2.10 on 2020-07-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_siteconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='maintenance_mode',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='body1',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='body4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_image',
            field=models.ImageField(default='nil', upload_to='post/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='sub_image',
            field=models.ImageField(blank=True, upload_to='post/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='sub_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
