# Generated by Django 2.2.10 on 2020-07-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200704_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_name2',
            field=models.CharField(default='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='Site', max_length=255),
        ),
    ]
