# Generated by Django 2.2.10 on 2020-07-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200704_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='slogan',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
