# Generated by Django 2.2.10 on 2020-07-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_siteconfiguration_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embed_code',
            field=models.TextField(blank=True),
        ),
    ]
