# Generated by Django 2.2.10 on 2020-07-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_image2',
            field=models.ImageField(blank=True, upload_to='post/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_image3',
            field=models.ImageField(blank=True, upload_to='post/%Y/%m/%d'),
        ),
    ]
