# Generated by Django 2.2.10 on 2020-07-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200707_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_mail',
            field=models.CharField(default='victoradenuga04@yahoo.com', max_length=500),
        ),
    ]
